const fs=require('fs');const BASE='/data/data/com.dsharnessmobile.shell/files/home/.dsh/workspaces/incoming/lxqw';
const listeners=Object.create(null);const dispatched=[];
global.window=global;
global.core={SocketManage:{prototype:{send(){}},getInstance:()=>({send:()=>{}})},Socket:{prototype:{}},ServiceDispatcher:{getInstance:()=>({hasEventListener:n=>!!listeners[n],dispatchEvent:e=>{dispatched.push(e.type);(listeners[e.type]||[]).forEach(f=>f(e.data));}})},Event:function(t,d,p){this.type=t;this.data=d;this.params=p;},Log:{print(){},warning(){},error(){}}};
global.ProtocolList={protocolList:{}};global.ALISDK={};global.egret={setTimeout:(f,t)=>setTimeout(f,t||0)};
['album_load_new','travel_load_note','clover_update','client_load_role','item_load_items'].forEach(n=>listeners[n]=[function(){}]);
eval(fs.readFileSync(BASE+'/new/semantic.js','utf8'));
eval(fs.readFileSync(BASE+'/new/defaults.js','utf8'));
eval(fs.readFileSync(BASE+'/new/rules.js','utf8'));
eval(fs.readFileSync(BASE+'/new/mock.js','utf8'));
const M=window.MockServer,ST=window.MOCK_STATE;
console.log('semantic protocols:',Object.keys(window.MOCK_SEMANTIC).length);
ST.gifts.push({item_id:3000,count:1});
ST.photos.push({id:1,pic_id:100});
console.log('travel_load_gift:',JSON.stringify(M.handle('travel_load_gift',{})));
console.log('album_load     :',JSON.stringify(M.handle('album_load',{})));
console.log('album_load_all :',JSON.stringify(M.handle('album_load_all',{})));
console.log('visit_load     :',JSON.stringify(M.handle('visit_load',{})).slice(0,220));
console.log('travel_load_note:',JSON.stringify(M.handle('travel_load_note',{})).slice(0,120));
