const fs=require('fs');const BASE='/data/data/com.dsharnessmobile.shell/files/home/.dsh/workspaces/incoming/lxqw';
global.window=global;
const listeners=Object.create(null);
global.core={SocketManage:{prototype:{send(){}},getInstance:()=>({send:()=>{}})},Socket:{prototype:{}},ServiceDispatcher:{getInstance:()=>({hasEventListener:n=>!!listeners[n],dispatchEvent:e=>{(listeners[e.type]||[]).forEach(f=>f(e.data));}})},Event:function(t,d,p){this.type=t;this.data=d;this.params=p;},Log:{print(){},warning(){},error(){}}};
global.ProtocolList={protocolList:{}};global.ALISDK={};global.egret={setTimeout:(f,t)=>setTimeout(f,t||0)};
function WeatherModel(){this.data={season:0,hours_type:0,weather:0};} WeatherModel.prototype.getSeasonKey=function(){return this.data.season+""+this.data.hours_type;};
global.WeatherModel=WeatherModel; global.MessageModel=function(){}; global.MessageModel.prototype={};
['visit_load','clover_update','item_load_items'].forEach(n=>listeners[n]=[function(){}]);
for (const f of ['semantic','defaults','rules','mock','iap','mail','activities','visitor','guard']) eval(fs.readFileSync(BASE+'/new/'+f+'.js','utf8'));
const M=window.MockServer,S=window.MOCK_SEMANTIC,ST=window.MOCK_STATE;
const provs=JSON.parse(fs.readFileSync(BASE+'/tables/visitors_json.json','utf8')).provinceList;
console.log("=== 1) visitor spawn payload ===");
window.MOCK_SPAWN_VISITOR();
var v=S['visit_load']().visitor;
console.log("   visitor:", JSON.stringify(v));
if (v) {
  var pk=String(v.city).split("_")[0];
  console.log("   province key '"+pk+"' in provinceList? ", Object.keys(provs).indexOf(pk)>=0);
  console.log("   partner in actionList? ", (v.partner>=0 && v.partner<=18));
  console.log("   carpet 1..8? ", v.carpet>=1 && v.carpet<=8);
} else console.log("   (no visitor - pool exhausted?)");
console.log("");
console.log("=== 2) guard vs the EXACT bug that crashed the game ===");
var bad = { visitor: { partner:7, name:"", title:0, expire_time:0, city:"辽宁城区", food:0, first:true, gift:{item_id:100000,count:20}, carpet:3 }, acquire: [] };
var out = window.MOCK_GUARD_CHECK("visit_load", bad);
console.log("   city WITHOUT underscore ->  visitor:", JSON.stringify(out.visitor));
var bad2 = { visitor: { partner:99, name:"", title:0, expire_time:0, city:"辽宁_城区", food:0, first:true, gift:{item_id:100000,count:20}, carpet:3 }, acquire: [] };
var out2 = window.MOCK_GUARD_CHECK("visit_load", bad2);
console.log("   partner 99 (invalid)   ->  visitor:", JSON.stringify(out2.visitor));
var badItem = { bag:[0, 99999, -1, 1], desk:[-1,-1,-1,-1,-1,-1,-1,-1], house:[{item_id:99999,count:1},{item_id:3,count:2}], bag_completed:0,bag_conflict:0,desk_conflict:0,gacha:{color_ball:-1} };
var out3 = window.MOCK_GUARD_CHECK("item_load_items", badItem);
console.log("   bag with 99999 -> ", JSON.stringify(out3.bag), "| house ->", JSON.stringify(out3.house));
console.log("");
console.log("=== 3) guard drop log ===");
console.log("   drops: " + JSON.stringify(window.MOCK_GUARD_DROPS()));
console.log("");
console.log("=== 4) layers / version ===");
console.log("   mock version:", M.version, "| semantic protocols:", Object.keys(S).length);
