const fs=require('fs');const BASE='/data/data/com.dsharnessmobile.shell/files/home/.dsh/workspaces/incoming/lxqw';
global.window=global;
const listeners=Object.create(null);
global.core={SocketManage:{prototype:{send(){}},getInstance:()=>({send:()=>{}})},Socket:{prototype:{}},ServiceDispatcher:{getInstance:()=>({hasEventListener:n=>!!listeners[n],dispatchEvent:e=>{(listeners[e.type]||[]).forEach(f=>f(e.data));}})},Event:function(t,d,p){this.type=t;this.data=d;this.params=p;},Log:{print(){},warning(){},error(){}}};
global.ProtocolList={protocolList:{}};global.ALISDK={};global.egret={setTimeout:(f,t)=>setTimeout(f,t||0)};
function WeatherModel(){this.data={season:0,hours_type:0,weather:0};} WeatherModel.prototype.getSeasonKey=function(){return this.data.season+""+this.data.hours_type;};
global.WeatherModel=WeatherModel; global.MessageModel=function(){}; global.MessageModel.prototype={};
['visit_load','clover_update'].forEach(n=>listeners[n]=[function(){}]);
eval(fs.readFileSync(BASE+'/new/semantic.js','utf8'));
eval(fs.readFileSync(BASE+'/new/defaults.js','utf8'));
eval(fs.readFileSync(BASE+'/new/rules.js','utf8'));
eval(fs.readFileSync(BASE+'/new/mock.js','utf8'));
eval(fs.readFileSync(BASE+'/new/iap.js','utf8'));
eval(fs.readFileSync(BASE+'/new/mail.js','utf8'));
eval(fs.readFileSync(BASE+'/new/activities.js','utf8'));
eval(fs.readFileSync(BASE+'/new/visitor.js','utf8'));
const M=window.MockServer,S=window.MOCK_SEMANTIC,ST=window.MOCK_STATE;
console.log('before: visitor=', JSON.stringify(S['visit_load']()));
console.log('spawn ->', window.MOCK_SPAWN_VISITOR());
const v=S['visit_load']().visitor;
console.log('visitor:', JSON.stringify(v));
const provs=JSON.parse(fs.readFileSync(BASE+'/tables/visitors_json.json','utf8')).provinceList;
console.log('  province valid?', Object.keys(provs).indexOf(String(v.city).split('_')[0]) >= 0, '| partner valid?', v.partner>=0 && v.partner<=18);
console.log('  carpet in 1..8?', v.carpet>=1 && v.carpet<=8);
console.log('open (first) ->', JSON.stringify(S['visit_open']()));
console.log('after: acquire=', JSON.stringify(ST.acquire), '| visitor=', ST.visitor);
console.log('semantic protocols:', Object.keys(S).length, '| mock version:', M.version);
